<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-9H2ESQ8I" failures="2" tests="2" name="Default test(failed)" time="0.024" errors="0" timestamp="15 May 2023 18:53:17 GMT">
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestOne" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGfeatures.FailedTestCases.getTestOne(FailedTestCases.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestTwo" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGfeatures.FailedTestCases.getTestTwo(FailedTestCases.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestTwo -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
</testsuite> <!-- Default test(failed) -->
