<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-9H2ESQ8I" failures="1" tests="1" name="Default test(failed)(failed)(failed)" time="0.021" errors="0" timestamp="15 May 2023 18:50:22 GMT">
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestOne" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGfeatures.FailedTestCases.getTestOne(FailedTestCases.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
  <testcase classname="testNGfeatures.FailedTestCases" name="getTestTwo" time="0.0">
    <ignored/>
  </testcase> <!-- getTestTwo -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
